common/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.login, name='login'),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('parent_registration', views.parent_registration, name='parentreg'),
    path('child_registration', views.child_registration, name='child_registration'),
    
    









]

daycare/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('daycare_admin/', include('daycare_admin.urls')),
    path('daycare_parent/', include('daycare_parent.urls')),
    path('daycare_staff/', include('daycare_staff.urls')),
]

daycare_admin/urls.py
from django.urls import path
from . import views


app_name = "daycare_admin"
urlpatterns = [
    path('', views.adminhome, name='admin_home'),
    path('staff_registration', views.staff_registration, name='staffreg'),
    path('report', views.report, name='report'),
    path('viewparent', views.viewparent, name='viewparent'),
    path('viewchild/<int:id>', views.viewchild, name='viewchild'),
    path('charge', views.charge, name='charge'),
    path('viewfeedback', views.viewfeedback, name='viewfeedback'),
    
    path('viewpayment', views.viewpayment, name='viewpayment'),
    path('viewstaff', views.viewstaff, name='viewstaff'),
    path('delete_view/<int:id>/', views.delete_view, name='delete_view'),



]

daycare_admin/models.py
from django.db import models 
from common.models import *
# Create your models here.

class IncidentReport(models.Model):
    parent_fk = models.ForeignKey(ParentRegister, on_delete=models.CASCADE)
    child_name = models.CharField(max_length=30)
    parent_email_id = models.CharField(max_length=30)
    description = models.TextField()
    current_status = models.TextField()
    incident_date = models.CharField(max_length=20)
    

    class Meta():
        db_table="incident_report"  

class StaffRegistration(models.Model):
    staff_name = models.CharField(max_length=30)
    staff_address = models.TextField()
    staff_email_id = models.CharField(max_length=30)
    staff_dob = models.CharField(max_length=30)
    staff_gender = models.CharField(max_length=20)
    staff_qualification = models.CharField(max_length=30)
    staff_mobile_no = models.CharField(max_length=30)
    staff_username = models.CharField(max_length=30)
    staff_password = models.CharField(max_length=30)

    class Meta():
        db_table = "staff_registration"

daycare_admin/views.py
from django.shortcuts import render,redirect
from django.shortcuts import get_object_or_404
from common.models import *
from daycare_parent.models import * 
from .models import * 
from  daycare_admin.models import *
from django.core.mail import send_mail
from django.conf import settings
import stripe


# Create your views here.
from django.views.generic.base import TemplateView

stripe.api_key = settings.STRIPE_SECRET_KEY


def adminhome(request):
    
    return render(request,"daycare_admin/admin_home.html")

def staff_registration(request):
    msg = ""
    if request.method == "POST":
        staffname = request.POST["staff_name"]
        staffaddress = request.POST["staff_address"]
        staffemail = request.POST["staff_email_id"]
        staffdob = request.POST["staff_dob"]
        staffgender = request.POST["staff_gender"]
        staffqualification =request.POST["staff_qualification"]
        staffphone = request.POST["staff_mobile_no"]
        staffusername = request.POST["staff_username"]
        staffpassword = request.POST["staff_password"]
        staff_exist = StaffRegistration.objects.filter(staff_email_id=staffemail)
        username_exist = StaffRegistration.objects.filter(staff_username=staffusername)
        if staff_exist:
            msg = "Email already exist"
        elif username_exist:
            msg = "Username already exist"

        else:
        
            staffreg = StaffRegistration(staff_name=staffname,staff_address=staffaddress,
                                        staff_email_id=staffemail,staff_dob=staffdob,staff_gender=staffgender,staff_qualification=staffqualification,
                                        staff_mobile_no=staffphone,
                                        staff_username=staffusername,staff_password=staffpassword)
            # staffreg.save()
            subject = "Calicut University Daycare Staff Registration"
            message = f"Hi {staffname}, \n\nYour Daycare login credentials is, \n\nUsername : {staffusername} \nPassword : {staffpassword} \n\nRegards \nDaycare Team"
            email_from = settings.EMAIL_HOST_USER
            email_to = [staffemail]
            send_mail(subject, message, email_from, email_to)
            staffreg.save()
            msg = "Staff Registration Successful"
        return render(request,"daycare_admin/staff_registration.html", {"message":msg})

    return render(request,"daycare_admin/staff_registration.html")

def viewstaff(request,):
    all_staffs = StaffRegistration.objects.all()

    return render(request, "daycare_admin/viewstaff.html",{"all_staffs":all_staffs})

def delete_view(request, id):
    item = get_object_or_404(StaffRegistration,id=id)
    item.delete()
    return redirect('daycare_admin/home')
    

def report(request):
    
    if request.method == "POST":
        child_name = request.POST["child_name"]
        parent_email_id = request.POST["parent_email_id"]
        description = request.POST["description"]
        current_status = request.POST["current_status"]
        report_date = request.POST["report_date"]
        parent_fk = ParentRegister.objects.filter(email_id=parent_email_id).first()
        print(parent_fk)
        if parent_fk is not None:
            report = IncidentReport(parent_fk=parent_fk,child_name=child_name, parent_email_id=parent_email_id, description=description, current_status=current_status,incident_date=report_date )
            report.save()
            message = "Report Sent!"
        else:
            message = "Please enter registered email address of the parent "
        return render(request,"daycare_admin/report.html",{'message':message})
    return render(request,"daycare_admin/report.html")

def viewparent(request):
    all_parents = ParentRegister.objects.all()
    

    return render(request,"daycare_admin/viewparent.html",{"all_parents":all_parents})

def viewchild(request, id):
    view_child = ChildRegister.objects.filter(parent_fk=id)
    print(view_child)
    return render(request,"daycare_admin/viewchild.html",{"all_child":view_child})

def viewpayment(request):

    return render(request,"daycare_admin/viewpayment.html")

def viewfeedback(request):
    all_feedback = ParentFeedback.objects.all()


    return render(request,"daycare_admin/viewfeedback.html",{"all_feedback":all_feedback})


def charge(request): #new
    if request.method == 'POST':
        charge = stripe.Charge.create(
            amount=500,
            currency='inr',
            description='Payment Gateway',
            source=request.POST['stripeToken']
        )
        return render(request,'charge.html')

daycare_admin/templates/daycare_admin/admin_home.html
{% extends 'daycare_admin/admin.html' %}
{% load static %}
{% block content %}
<div class="container-fluid vh-100 admin_image">
    
     <div class="row pt-md-5 ms-md-5 me-md-5">
        <div class="col-md-6 mt-md-3">


            <div class="card card_style">



                <div class="card-body card_up">
                    <h1 class="card_title fw-bold text-light">5</h1>

                    <div class="d-flex align-items-center">
                        <img src="{% static 'admin_img/card.jpg' %}" alt="" width="45" height="auto" class="img-fluid">
                        <div class="ps-md-3">
                            <h3 class="text-light card_up">New Enrollments</h3>


                        </div>
                    </div>
                </div>

            </div>








        </div>
        <div class="col-md-6 mt-md-3">


            <div class="card card_style">


                <div class="card-body card_up">
                    <h1 class="card_title fw-bold text-light">2</h1>

                    <div class="d-flex align-items-center">
                        <img src="{% static 'admin_img/payment.jpg' %}" alt="" width="50" height="auto" class="img-fluid">
                        <div class="ps-md-3">
                            <h3 class="text-light card_up">New Payments</h3>


                        </div>
                    </div>
                </div>


            </div>


        </div>
    </div>
    <!-- End Sales Card -->

</div>
{% endblock %}

daycare_admin/templates/daycare_admin/report.html
{% extends 'daycare_admin/admin.html' %}
{% block content %}
{% load static %}

<div class=" vh-100 report_pic align-items-center">
    <div class="container p-5">
        <h1 class="text-uppercase text-center fw-bold text-danger py-2 report_font">medical incident reporting</h1>
        <form method="POST" class="no-validation">
            {% csrf_token %}
            <div class="row py-1">
                <div class="col-3">

                    <label class="form-label  text-dark report_font" for="childname" required>Child Name:</label>
                </div>
                <div class="col-9">
                    <input class="form-control" type="text" id="childname" name="child_name">
                </div>
            </div>
    
    <div class="row py-1">
        <div class="col-3">

            <label class="form-label text-dark report_font" for="incidentdate" required>Parent Email_Id:</label>
        </div>
        <div class="col-9">
            <input class="form-control" type="text" id="parentemail" name="parent_email_id">
        </div>
    </div>

<div class="row py-1">
    <div class="col-3">

        <label class="form-label text-dark report_font" for="description">Description:</label>
    </div>
    <div class="col-9">
        <textarea class="form-control" type="address" id="description" name="description" row="4"
            placeholder="Type the incident name ,consultant details,docterts name,given first aid and prescription details "
            required></textarea>
    </div>
</div>

<div class="row py-1">
    <div class="col-3">

        <label class="form-label report_font text-dark" for="current_status" required>Current Status:</label>
    </div>
    <div class="col-9">
        <input class="form-control" type="text" id="current_status" name="current_status" placeholder="Type child current status here">
    </div>
</div>



<div class="row py-1">
    <div class="col-3">

        <label class="form-label text-dark report_font" for="reportdate" required>Incident Date:</label>
    </div>
    <div class="col-9">
        <input class="form-control" type="date" id="reportdate" name="report_date">
    </div>
</div>

<div class="text-center login_head py-1">
    <input class="btn btn-danger btn-lg " id="submit" type="submit" value="Generate Report">

</div>
<div class="container report_font text-center" style="color: #a3220bcd;" id="">{{message}}</div>



</form>

</div>
</div>

{% endblock %}

daycare_admin/templates/daycare_admin/viewchild.html
{% extends 'daycare_admin/admin.html' %}
{% load static %}
{% block content %}
    <!-- <div class=" vh-100"> -->
        <div class="container p-5">
            <h1 class="text-uppercase text-center fw-bold text-success bg-dark pb-md-2 pt-md-2">Child registrations
            </h1>
            <table class="table-sm bg-light">
                <thead>
                    <tr>
                        <th scope="col">Child Name</th>
                        <th scope="col">Date of Birth</th>
                        <th scope="col">Height</th>
                        <th scope="col">Weight</th>
                        <th scope="col">Gender</th>
                        <th scope="col">Medical Information</th>
                        <th scope="col">Dieatry Preferences</th>
                        <th scope="col">PickUp List</th>
                        <th scope="col">Parental Preferences</th>
                    </tr>
                </thead>
                <tbody>
                    {% for child in all_child %}
                    <tr>
                        <td>{{child.name}}</td>
                        <td>{{child.dateofbirth}}</td>
                        <td>{{child.height}}</td>
                        <td>{{child.weight}}</td>
                        <td>{{child.gender}}</td>
                        <td>{{child.medical_information}}</td>
                        <td>{{child.dieatry_preferences}}</td>
                        <td>{{child.pickup_list}}</td>
                        <td>{{child.parental_preferences}}</td>
                        <td><a href="{% url 'daycare_admin:viewchild' child.id %}" class="btn btn-primary btn-sm">Click</a></td>
                    </tr>
                    {% endfor %}
                   
                </tbody>    
            </table>
        </div>
    <!-- </div> -->
{% endblock %}

daycare_admin/templates/daycare_admin/viewfeedback.html
{% extends 'daycare_admin/admin.html' %}
{% load static %}
{% block content %}

    <div class=" vh-100 admin_image overflow-auto                                   ">
        <div class="container pt-md-5">
            <h1 class="text-uppercase text-center fw-bold text-success bg-dark pb-md-2 pt-md-2">parent feedbacks
            </h1>
            <table class="bg-light table table-sm fw-bold card_style">
                <thead>
                    <tr>
                        <th scope="col">Parent_Name</th>
                        <th scope="col">Phone_No</th>
                        <th scope="col">Email_id</th>
                        <th scope="col">feedback</th>
                        <th scope="col">Date</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for feedback in all_feedback %}

                    <tr>
                        <th>{{feedback.parent_fk.name}}</th>
                        <td>{{feedback.parent_fk.phone_no}}</td>
                        <td>{{feedback.parent_fk.email_id}}</td>
                        <td>{{feedback.feed_description}}</td>
                        <td>{{feedback.feed_date}}</td>
                        
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

daycare_admin/templates/daycare_admin/viewparent.html
{% extends 'daycare_admin/admin.html' %}
{% load static %}
{% block content %}
    <!-- <div class=" vh-100"> -->
        <div class="container p-5">
            <h1 class="text-uppercase text-center fw-bold text-success bg-dark pb-md-2 pt-md-2">parent registration Details
            </h1>
            <table class="table-sm bg-light">
                <thead>
                    <tr>
                        <th scope="col">Parent FirstName</th>
                        <th scope="col">Parent LastName</th>
                        <th scope="col">Email</th>
                        <th scope="col">Address</th>
                        <th scope="col">Phone_No</th>
                        <th scope="col">Occupation</th>
                        <th scope="col">Gender</th>
                        <th scope="col">View Child</th>
                    </tr>
                </thead>
                <tbody>
                    {% for parent in all_parents %}
                    <tr>
                        <td>{{parent.name}}</td>
                        <td>{{parent.last_name}}</td>
                        <td>{{parent.email_id}}</td>
                        <td>{{parent.address}}</td>
                        <td>{{parent.phone_no}}</td>
                        <td>{{parent.occupation}}</td>
                        <td>{{parent.gender}}</td>
                        <td><a href="{% url 'daycare_admin:viewchild' parent.id %}" class="btn btn-primary btn-sm">Click</a></td>
                    </tr>
                    {% endfor %}
                   
                </tbody>    
            </table>
        </div>
    <!-- </div> -->
{% endblock %}

daycare_admin/templates/daycare_admin/viewpayment.html
<!-- {% extends 'daycare_admin/admin.html' %}
{% load static %}
{% block content %} -->



    <!-- <div class=" vh-100">
        <div class="container pt-md-5">
            <h1 class="text-uppercase text-center fw-bold bg-dark text-success pb-md-2 pt-md-2">payment details
            </h1>
            <table class="bg-light table table-sm border-dark text-light card_style">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Date</th>
                        
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>shilpa</th>
                        <td>2000</td>
                        <td>3/10/2023</td>
                        
                    </tr>
                    <tr>
                        <th>saranya</th>
                        <td>2000</td>
                        <td>5/08/2023</td>
                        
                    </tr>
                </tbody>
            </table>
        </div>
    </div> -->
<!-- <h1>Successfully paid your Bill.</h1>

{% endblock %} -->

daycare_admin/templates/daycare_admin/viewstaff.html
{% extends 'daycare_admin/admin.html' %}
{% load static %}
{% block content %}
     <div class=" vh-100">
        <div class="container p-5">
            <h1 class="text-uppercase text-center fw-bold text-success bg-dark pb-md-2 pt-md-2">STAFF DETAILS
            </h1>
            <table class="table-sm bg-light">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">Email_Id</th>
                        <th scope="col">Date_of_birth</th>
                        <th scope="col">Gender</th>
                        <th scope="col">Qualification</th>
                        <th scope="col">Mobile_No</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for staff in all_staffs %}
                    <tr>
                        <td>{{staff.staff_name}}</td>
                        <td>{{staff.staff_address}}</td>
                        <td>{{staff.staff_email_id}}</td>
                        <td>{{staff.staff_dob}}</td>
                        <td>{{staff.staff_gender}}</td>
                        <td>{{staff.staff_qualification}}</td>
                        <td>{{staff.staff_mobile_no}}</td>
                        
                        <td><a href="{% url 'daycare_admin:delete_view' staff.id %}" class="btn btn-primary btn-sm">delete</a></td>
                        
                    </tr>
                    {% endfor %}
                   
                </tbody>    
            </table>
        </div>
     </div>
{% endblock %}