common/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.login, name='login'),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('parent_registration', views.parent_registration, name='parentreg'),
    path('child_registration', views.child_registration, name='child_registration'),
    
    









]

daycare/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('daycare_admin/', include('daycare_admin.urls')),
    path('daycare_parent/', include('daycare_parent.urls')),
    path('daycare_staff/', include('daycare_staff.urls')),
]

daycare_parent/urls.py
from django.urls import path
from . import views


app_name = "daycare_parent"
urlpatterns = [
    # path('',views.home,name="home")
    path('', views.parenthome, name='parenthome'),
    path('feedback', views.feedback, name='feedback'),
    path('profile', views.profile, name='profile'),
    path('edit/<int:id>', views.edit_child, name='edit_child'),
    # path('payment', views.payment, name='payment'),
    path('viewnutritions', views.viewnutritions, name='viewnutritions'),
    path('viewreport', views.viewreport, name='viewreport'),
    path('viewattendance', views.viewattendance, name='viewattendance'),
    path('payment', views.ViewPayment.as_view(), name='payment'),
    path('charge', views.charge, name='charge'),
    path('logout', views.logout, name="logout"),

]

daycare_parent/models.py
from django.db import models
from common.models import ParentRegister

# Create your models here.
class ParentFeedback(models.Model):
    parent_fk = models.ForeignKey(ParentRegister,on_delete=models.CASCADE)
    feed_description= models.TextField()
    feed_date = models.DateField()
    
    class Meta():
        db_table="parent_feedback"

daycare_parent/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from .models import *
from daycare_admin.models import *
import datetime
from daycare_staff.models import *
from django.views.generic.base import TemplateView
import stripe
# Create your views here.


def parenthome(request):
    parent = ParentRegister.objects.get(id=request.session['user_id'])

    return render(request, "daycare_parent/parenthome.html", {"parent": parent})


def payment(request):

    return render(request, "daycare_parent/payment.html")
def charge(request):
    if request.method == 'POST':
        stripe.api_key = settings.STRIPE_SECRET_KEY

        try:
            intent = stripe.PaymentIntent.create(
                amount=1099,
                currency='inr',
                payment_method_types=['card'],
            )
        except stripe.error.StripeError as e:
            # Handle error here
            return render(request, 'daycare_parent/error.html', {'message': 'Your card has been declined.'})
    return render(request, "daycare_parent/charge.html")

class ViewPayment(TemplateView):
    template_name = 'daycare_parent/payment.html'

    def get_context_data(self, **kwargs): #new
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        return context


def profile(request):
    parent_fk = request.session['user_id']
    all_child = ChildRegister.objects.filter(parent_fk=parent_fk)

    return render(request, "daycare_parent/profile.html", {"all_child": all_child})


def edit_child(request, id):
    child = ChildRegister.objects.get(id=id)
    if request.method == 'POST':
        name = request.POST['childname']
        dob = request.POST['childdob']
        gender = request.POST['childgender']
        height = request.POST['childheight']
        weight = request.POST['childweight']
        medical = request.POST['childmedical']
        dieatry = request.POST['childdieatry']
        pickup = request.POST['childpickup']
        preferences = request.POST['childpreferences']
        ChildRegister.objects.filter(id=id).update(
            name=name,
            # dateofbirth=dob,
            height=height,
            weight=weight,
            gender=gender,
            medical_information=medical,
            dieatry_preferences=dieatry,
            pickup_list=pickup,
            parental_preferences=preferences
        )
        return redirect("daycare_parent:profile")
    return render(request, "daycare_parent/edit_child.html", {"child": child})


def feedback(request):

    if request.method == "POST":
        feed_description = request.POST["feed_description"]
        user_id = request.session["user_id"]
        parent_fk = ParentRegister.objects.get(id=user_id)
        feed_date = datetime.datetime.now()
        feedback = ParentFeedback(
            parent_fk=parent_fk, feed_description=feed_description, feed_date=feed_date)
        feedback.save()
        message = "Thank you for submitting feedback!"
        return render(request, "daycare_parent/feedback.html", {"message": message})
    return render(request, "daycare_parent/feedback.html")


def viewreport(request):

    parent_id = request.session['user_id']

    reports = IncidentReport.objects.filter(parent_fk=parent_id)

    return render(request, "daycare_parent/viewreport.html", {"reports": reports})


def viewattendance(request):

    return render(request, "daycare_parent/viewattendance.html")





def viewnutritions(request):
    user_id = request.session['user_id']
    child = ChildRegister.objects.filter(parent_fk=user_id)
    print(child)
    all_child = []
    for i in child:
        nutritions = Nutritions.objects.get(child_fk=i.id)
        all_child.append(nutritions)
    print(all_child)
    return render(request, "daycare_parent/viewnutritions.html", {"all_child":all_child})


def logout(request):

    del request.session['user_id']
    request.session.flush()
    return redirect('home')

daycare_parent/templates/daycare_parent/charge.html
{% extends 'daycare_parent/parent.html' %}
{% load static %}
{% block content %}
<h1 class="text-center bg-light">Successfully paid your bill</h1>
{% endblock %}

daycare_parent/templates/daycare_parent/edit_child.html
{% extends 'daycare_parent/parent.html' %}
{% load static %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <div class="row border bg-success border-2 p-3 mx-auto ">

        <div class="mb-2 col-md-6">
            <label for="child_name0" class="form-label text_dark">Child Name</label>
            <input type="text" class="form-control" name="childname" id="child_name0" value="{{child.name}}">
        </div>
        <div class="mb-2 col-md-6">
            <label for="child_dateofbirth0" class="form-label text_dark">Date of
                Birth</label>
            <input type="text" class="form-control" name="childdob" id="child_dateofbirth0" value="{{child.dateofbirth}}">
        </div>
        <div class="row">
            <div class="mb-2 col-md-3">
                <label for="child_height0" class="form-label text_dark">Height</label>
                <input type="text" class="form-control" name="childheight" id="child_height0" value="{{child.height}}">
            </div>
            <div class="mb-2 col-md-3">
                <label for="child_weight0" class="form-label text_dark">Weight</label>
                <input type="text" class="form-control" name="childweight" id="child_weight0" value="{{child.weight}}">
            </div>
            <div class="mb-2 col-md-6">
                <label for="child_gender" class="form-label text_dark">Gender</label>
                <div>
                    {% if child.gender == "male" %}
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" checked
                             name="childgender" id="child_gender0" value="male">
                        <label class="form-check-label text_dark"
                            for="child_gender0">Male</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio"
                            name="childgender" id="child_gender0" value="female">
                        <label class="form-check-label text_dark"
                            for="child_gender0">Female</label>
                    </div>
                    {% else %}
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" 
                             name="childgender" id="child_gender0" value="male">
                        <label class="form-check-label text_dark"
                            for="child_gender0">Male</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" checked
                            name="childgender" id="child_gender0" value="female">
                        <label class="form-check-label text_dark"
                            for="child_gender0">Female</label>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="mb-2 col-md-6">
                <label for="child_medical_information0"
                    class="form-label text_dark">Medical
                    Information</label>
                <textarea class="form-control" name="childmedical" id="child_medical_information0"
                    rows="1">{{child.medical_information}}</textarea>
            </div>
            <div class="mb-2 col-md-6">
                <label for="child_dieatry0" class="form-label text_dark">Dieatry
                    Prefrences/Restrictions</label>
                <textarea class="form-control" name="childdieatry" id="child_dieatry0" rows="1">{{child.dieatry_preferences}}</textarea>
            </div>
        </div>
        <div class="row">
            <div class="mb-2 col-md-6">
                <label for="child_pickup_list0" class="form-label text_dark">Authorized
                    Pickup
                    list</label>
                <textarea class="form-control" name="childpickup" id="child_pickup_list0" 
                    rows="1">{{child.pickup_list}}</textarea>
            </div>
            <div class=" col-md-6">
                <label for="child_parental_preferences0"
                    class="form-label text_dark">Parental
                    Preferences</label>
                <textarea class="form-control" name="childpreferences" id="child_parental_preferences0" 
                    rows="1">{{child.parental_preferences}}</textarea>
            </div>
        </div>
    </div>
    <div class="d-flex justify-content-center ">
    <button class="btn btn-primary w-100" type="submit">Update</button>
</div>

</form>
{% endblock %}

daycare_parent/templates/daycare_parent/error.html
{% extends 'daycare_parent/parent.html' %}
{% load static %}
{% block content %}
<h1 class="text-center bg-light">{{message}}</h1>
{% endblock %}

daycare_parent/templates/daycare_parent/feedback.html
{% extends 'daycare_parent/parent.html' %}
{% load static %}
{% block content %}

<div class=" vh-100 feedback_pic d-flex align-items-center">
    <div class="container p-5">
        <h2 class="text-uppercase text-center fw-bold text-dark report_font">give us your feedback!</h2>
        <form class="px-5 pt-2" method="POST">
            {% csrf_token %}  
                <div class="text-center mb-2">
                    <textarea class="" id="feedback" cols="50" rows="8" name="feed_description"
                        placeholder="Help us to improve with your feedback"></textarea>
                </div>
          

            <div class="row">
                <div class="col-md-12 d-flex justify-content-center">
                <input class="btn btn-danger btn-lg" id="submit" type="submit" value="Post Feedback">
            </div>
        </div>
            <div class="container report_font text-center" style="color: blue;" id="">{{message}}</div>
            

        </form>

    </div>
</div>
<!-- <script>
    $(document).ready(function () {
        // Add a click event listener to the submit button
        $('#submit').click(function (event) {
            event.preventDefault(); // Prevent the form from submitting

            // Display the "Thank you" message
            $('#feedback1').append('<center>Thank you for submitting feedback!</center>');
            $("#feedback1").css("color", "blue");

            // Reset the form (optional)
            $('#feedback')[0].reset();
        });
    });
</script> -->

{% endblock %}

daycare_parent/templates/daycare_parent/parenthome.html
{% extends 'daycare_parent/parent.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
    <head><title>hello</title></head>
    <body>
 <div class="container-fluid parent_font py-4 ps-md-5 ms-md-5">
    
    <h3 class="fst-italic text-light  font_2 text-capitalize">let your children soar with us!</h3>
</div>
{% endblock %}

daycare_parent/templates/daycare_parent/payment.html
{% extends 'daycare_parent/parent.html' %}
{% load static %}
{% block content %}

<h2>PAY 2000 MONTHLY</h2>
<form action="{% url 'daycare_parent:charge' %}" method="POST">
    {% csrf_token %}
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="{{ key }}"
    data-description="Payment Gateway"
    data-amount="500"
    data-locale="auto">

</script>
</form>

<!-- <div class="container vh-100">
    <div class="container py-5">
        <h2 class="text-upperc  ase text-center pb-md-3 fw-bold text-light report_font">payment form</h2>
        <div class="container"></div>
        <div class="card text-dark bg-secondary px-md-5 mx-md-5">
            <p class="text-center text-dark py-md-1">Payment Details</p>
            <div class="row gx-md-5">
                <div class="col-md-12">
                    <div class="flex-column">
                        <p class="text mb-1">Person Name (On Card)</p>
                        <input class="form-control mb-1" id="name" type="text" placeholder="Name">
                        <div class="invalid-feedback" id="name_error">
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="flex-column">
                        <p class="text mb-1">Card Number</p>
                        <input class="form-control mb-1" id="cardno" type="text" placeholder="1234 5678 435678">
                        <div class="invalid-feedback" id="cardno_error">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="flex-column">
                        <p class="text mb-1">Expiry</p>
                        <input class="form-control mb-1" id="expiry" type="text" placeholder="MM/YYYY">
                        <div class="invalid-feedback" id="expiry_error">
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="flex-column">
                        <p class="text mb-1">CVV/CVC</p>
                        <input class="form-control mb-2 pt-2 " id="cvv" type="password" placeholder="*">
                        <div class="invalid-feedback" id="cvv_error">
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="btn btn-primary mb-2">
                        <span class="ps-3" id="pay">Pay Now</span>
                        <span class="fas fa-arrow-right"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $("#name_error").hide();
        let nameError = true;
        $("#name").keyup(function () {
            validateName();
        });

        function validateName() {
            let nameValue = $("#name").val();
            if (nameValue.length == "") {
                $("#name_error").show();
                document.getElementById("name").style.borderColor = 'red'
                document.getElementById("name_error").innerHTML = "*Please fill this field"
                nameError = false;
                return false;
            } else {
                document.getElementById("name").style.borderColor = ''
                document.getElementById("name_error").innerHTML = ""
                $("#name_error").hide();
            }
        }
        $("#cardno_error").hide();
        let cardnoError = true;
        $("#cardno").keyup(function () {
            validateCardno();
        }); -->

        <!-- function validateCardno() {
            let cardnoValue = $("#cardno").val();
            if (cardnoValue.length == "") {
                $("#cardno_error").show();
                document.getElementById("cardno").style.borderColor = 'red'
                document.getElementById("cardno_error").innerHTML = "*Please fill this field"
                cardnoError = false;
                return false;
            } else {
                document.getElementById("password").style.borderColor = ''
                document.getElementById("password_error").innerHTML = ""
                $("#cardno_error").hide();
            }
        }
        $("#expiry_error").hide();
        let expiryError = true;
        $("#expiry").keyup(function () {
            validateExpiry();
        });

        function validateExpiry() {
            let expiryValue = $("#expiry").val();
            if (expiryValue.length == "") {
                $("#expiry_error").show();
                document.getElementById("expiry").style.borderColor = 'red'
                document.getElementById("expiry_error").innerHTML = "*Please fill this field"
                expiryError = false;
                return false;
            } else {
                document.getElementById("expiry").style.borderColor = ''
                document.getElementById("expiry_error").innerHTML = ""
                $("#expiry_error").hide();
            }
        }
        $("#cvv_error").hide();
        let cvvError = true;
        $("#cvv").keyup(function () {
            validateCvv();
        });

        function validateCvv() {
            let cvvValue = $("#cvv").val();
            if (cvvValue.length == "") {
                $("#cvv_error").show();
                document.getElementById("cvv").style.borderColor = 'red'
                document.getElementById("cvv_error").innerHTML = "*Please fill this field"
                cvvError = false;
                return false;
            } else {
                document.getElementById("cvv").style.borderColor = ''
                document.getElementById("cvv_error").innerHTML = ""
                $("#cvv_error").hide();
            }
        }
        $("#pay").click(function () {
            validateName();
            validateCardno();
            validateExpiry();
            validateCvv();

            if (nameError == true && cardnoError == true && expiryError == true && cvvError == true) {
                return true;
            } else {
                return false;
            }

        });


    })

</script> -->

{% endblock %}

daycare_parent/templates/daycare_parent/profile.html
{% extends 'daycare_parent/parent.html' %}
{% load static %}
{% block content %}
    <!-- <div class=" vh-100"> -->
        <div class="container p-5">
            <h1 class="text-uppercase text-center fw-bold text-success bg-dark pb-md-2 pt-md-2">Child Profile
            </h1>
            <table class="table-sm bg-light">
                <thead>
                    <tr>
                        <th scope="col">Child Name</th>
                        <th scope="col">Date of Birth</th>
                        <th scope="col">Height</th>
                        <th scope="col">Weight</th>
                        <th scope="col">Gender</th>
                        <th scope="col">Medical Information</th>
                        <th scope="col">Dieatry Preferences</th>
                        <th scope="col">PickUp List</th>
                        <th scope="col">Parental Preferences</th>
                        <th scope="col">View/Edit</th>
                    </tr>
                </thead>
                <tbody>
                    {% for child in all_child %}
                    <tr>
                        <td>{{child.name}}</td>
                        <td>{{child.dateofbirth}}</td>
                        <td>{{child.height}}</td>
                        <td>{{child.weight}}</td>
                        <td>{{child.gender}}</td>
                        <td>{{child.medical_information}}</td>
                        <td>{{child.dieatry_preferences}}</td>
                        <td>{{child.pickup_list}}</td>
                        <td>{{child.parental_preferences}}</td>
                        <td><a href="{% url 'daycare_parent:edit_child' child.id %}" class="btn btn-primary btn-sm">Edit</a></td>
                    </tr>
                    {% endfor %}
                   
                </tbody>    
            </table>
        </div>
    <!-- </div> -->
{% endblock %}

daycare_parent/templates/daycare_parent/viewattendance.html
{% extends 'daycare_parent/parent.html' %}
{% load static %}
{% block content %}

    <div class=" vh-100 attendance">
        <div class="container pt-md-5 ps-md-4 pe-md-4">
            <h2 class="text-uppercase text-center fw-bold text-primary report_font pb-4">attendance register</h2>
            <table class="table table-sm border-white text-white nutrition_style card_style">
                <thead>
                  <tr>
                    <th scope="col">Sl No.</th>
                    <th scope="col">Child_Name</th>
                    <th scope="col">Date</th>
                    <th scope="col">Attendace_Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Hellen</td>
                    <td>20/8/2023</td>
                    <td>present</td>
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>vyom</td>
                    <td>20/8/2023</td>
                    <td>present</td>

                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td>shiya</td>
                    <td>20/8/2023</td>
                    <td>absent</td>
                </tbody>
              </table>
            </div>
            </div>
            
{% endblock %}

daycare_parent/templates/daycare_parent/viewnutritions.html
{% extends 'daycare_parent/parent.html' %}
{% load static %}
{% block content %}

<div class=" vh-100 nutritions">
    <div class="container pt-md-5 ps-md-4 pe-md-4">
        <h2 class="text-uppercase text-center fw-bold text-success card_style report_font  pt-md-2 pb-md-2">advanced
            nutritions planning
        </h2>
        <table class="table table-sm border-dark text-dark nutrition_style">
            <thead>
                <tr>

                    <th scope="col">Child_Name</th>
                    <th scope="col">CEREALS</th>
                    <th scope="col">PROTEINS</th>
                    <th scope="col">FRUITS</th>
                    <th scope="col">DAIRY</th>
                    <th scope="col">NOTES</th>


                </tr>
            </thead>
            <tbody>
                {% for child in all_child %}
                <tr>
                    <td>{{child.child_fk.name}}</td>
                    <td>
                        <table>
                            <thead>
                                <tr>
                                    <th>Items|</th>
                                    <th>Quantity/day</th>


                                </tr>
                            </thead>
                            <tbody>
                                {% for i in child.cereals.cereal %}
                                <tr>
                                    <td>{{i.cereal}}</td>
                                    <td>{{i.quantity}}</td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </td>
                    <td>
                        <table>
                            <thead>
                                <tr>
                                    <th>Items|</th>
                                    <th>Quantity/day</th>


                                </tr>
                            </thead>
                            <tbody>
                                {% for i in child.proteins.protein %}
                                <tr>
                                    <td>{{i.protein}}</td>
                                    <td>{{i.quantity}}</td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </td>
                    <td>
                        <table>
                            <thead>
                                <tr>
                                    <th>Items|</th>
                                    <th>Quantity/day</th>


                                </tr>
                            </thead>
                            <tbody>
                                {% for i in child.fruits.fruit %}
                                <tr>
                                    <td>{{i.fruit}}</td>
                                    <td>{{i.quantity}}</td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </td>
                    <td>
                        <table>
                            <thead>
                                <tr>
                                    <th>Items|</th>
                                    <th>Quantity/day</th>


                                </tr>
                            </thead>
                            <tbody>
                                {% for i in child.dairy.dairy %}
                                <tr>
                                    <td>{{i.dairy}}</td>
                                    <td>{{i.quantity}}</td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </td>


                    <td>{{child.notes}}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

daycare_parent/templates/daycare_parent/viewreport.html
{% extends 'daycare_parent/parent.html' %}
{% load static %}
{% block content %}

    <div class=" vh-100 report_back">
        <div class="container pt-md-5 ps-md-3 pe-md-3">
            <h2 class="text-uppercase text-center fw-bold text-dark card_style report_font  pt-md-2 pb-md-2">child medical status 
            </h2>
            {% if reports %}
            <table class="table table-sm border-dark text-dark nutrition_style">
                <thead>
                    <tr>
                        
                        <th scope="col">Child_Name</th>
                        <th scope="col">parent_email_id</th>
                        <th scope="col">Description</th>
                        <th scope="col">current_status</th>
                        <th scope="col">Incident_date</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        {% for report in reports %}
                       
                        <td>{{report.child_name}}</td>
                        <td>{{report.parent_email_id}}</td>
                        <td>{{report.description}}</td>
                        <td>{{report.current_status}}</td>
                        <td>{{report.incident_date}}</td>
                        </tr>
                        {% endfor %}

                </tbody>
            </table>
            {% else %}
            <div class="d-flex justify-content-center">
            <h4>Curently you have no child incident reports.</h4>
        </div>
            {% endif %}
        </div>
    </div>

{% endblock %}