common/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.login, name='login'),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('parent_registration', views.parent_registration, name='parentreg'),
    path('child_registration', views.child_registration, name='child_registration'),
    
    









]

daycare/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('daycare_admin/', include('daycare_admin.urls')),
    path('daycare_parent/', include('daycare_parent.urls')),
    path('daycare_staff/', include('daycare_staff.urls')),
]

daycare_staff/urls.py
from django.urls import path
from . import views


app_name = "daycare_staff"
urlpatterns = [
    # path('',views.home,name="home")
    path('',views.staffhome,name="staffhome"),
    path('viewprofile',views.viewprofile,name='viewprofile'), 
    path('attendance',views.attendance,name='attendance'),
    path('nutritions/<int:id>',views.nutritions,name='nutritions'),
    path('vaccination',views.vaccination,name='vaccination'),
    
    
]

daycare_staff/models.py
from django.db import models

from common.models import *

# Create your models here.


class Nutritions(models.Model):
    child_fk = models.ForeignKey(ChildRegister,on_delete=models.CASCADE)
    fruits = models.JSONField(blank=True, default=list)
    dairy = models.JSONField(blank=True, default=list)
    proteins = models.JSONField(blank=True, default=list)
    cereals = models.JSONField(blank=True, default=list)
    notes = models.TextField()


    class Meta():
        db_table = "nutritions"

daycare_staff/views.py
from django.shortcuts import render,redirect
from common.models import *
from daycare_admin.models import *
from .models import *
# from celery import task
from datetime import date
from django.core.mail import send_mail
from .models import ChildRegister
# Create your views here.


def staffhome(request):

    return render(request, "daycare_staff/staffhome.html")


def viewprofile(request):
    view_child = ChildRegister.objects.all()
    print(view_child)
    return render(request, "daycare_staff/viewprofile.html", {"all_child": view_child})


def attendance(request):

    return render(request, "daycare_staff/attendance.html")


def nutritions(request, id):
    if request.method == 'POST':
        print("workint 1")
        cereals = request.POST.getlist('cereals[]')
        proteins = request.POST.getlist('proteins[]')
        fruits = request.POST.getlist('fruits[]')
        dairys = request.POST.getlist('dairy[]')
        notes = request.POST['notes']
        # protein_notes = request.POST['protein_notes']
        # fruit_notes = request.POST['fruit_notes']
        # dairy_notes = request.POST['dairy_notes']
        
        nutrition_check = Nutritions.objects.filter(id=id).first()
        child_fk = ChildRegister.objects.get(id=id)
    

        # Cereal
        all_cereals = []
        cereal_dict = {}
        cereal_nutrition = []
        for cereal in cereals:
            cereal_data = {}
            quantity_key = cereal + '_quantity'
            quantity = request.POST[quantity_key]
            print(cereal, quantity)
            cereal_data["cereal"] = cereal
            cereal_data["quantity"] = quantity
            cereal_nutrition.append(cereal_data)

        cereal_dict["cereal"] = cereal_nutrition
        
        all_cereals.append(cereal_dict)
        
        # Protins
        all_protins = []
        protein_dict = {}
        protein_nutrition = []
        for protein in proteins:
            protein_data = {}
            protin_data = {}
            quantity_key = protein + '_quantity'
            quantity = request.POST[quantity_key]
            print(protein, quantity)
            protin_data["quantity"] = quantity
            protin_data["protein"] = protein
            protein_nutrition.append(protin_data)

        protein_dict["protein"] = protein_nutrition
        # protein_dict["notes"] = protein_notes
        all_protins.append(protein_dict)

        # Fruits
        all_fruits = []
        fruit_dict = {}
        fruit_nutrition = []
        for fruit in fruits:
            fruit_data = {}
            quantity_key = fruit + '_quantity'
            quantity = request.POST[quantity_key]
            print(fruit, quantity)
            fruit_data["quantity"] = quantity
            fruit_data["fruit"] = fruit
            fruit_nutrition.append(fruit_data)
        fruit_dict["fruit"] = fruit_nutrition
        # fruit_dict["notes"] = fruit_notes
        all_fruits.append(fruit_dict)

        # Dairy
        all_dairys = []
        dairy_dict = {}
        dairy_nutrition = []
        for dairy in dairys:
            dairy_data = {}
            quantity_key = dairy + '_quantity'
            quantity = request.POST[quantity_key]
            print(dairy, quantity)
            dairy_data["quantity"] = quantity
            dairy_data["dairy"] = dairy
            dairy_nutrition.append(dairy_data)
        dairy_dict["dairy"] = dairy_nutrition
        # dairy_dict["notes"] = dairy_notes
        all_dairys.append(dairy_dict)

        if nutrition_check:
            Nutritions.objects.filter(id=id).update(cereals=cereal_dict,proteins=protein_dict,fruits=fruit_dict,dairy=dairy_dict,notes=notes)
            return redirect("daycare_staff:viewprofile")
        else:
            nutrition = Nutritions(child_fk=child_fk,cereals=cereal_dict,proteins=protein_dict,fruits=fruit_dict,dairy=dairy_dict,notes=notes)
            nutrition.save()
            return redirect("daycare_staff:viewprofile")
        
    return render(request, "daycare_staff/nutritions.html")

def vaccination():
    # def send_vaccination_alerts():
    # Get the current date
    current_date = date.today()

    # Fetch children whose vaccination is due on the current date
    children = ChildRegister.objects.all()

    for child in children:
        # Calculate the child's age in months
        age_in_months = (current_date.year - child.date_of_birth.year) * 12 + (current_date.month - child.date_of_birth.month)

        # Get the recommended vaccinations for the child's age from the vaccination schedule
        recommended_vaccinations = get_recommended_vaccinations(age_in_months)

        # Send vaccination alerts to parent emails
        if recommended_vaccinations:
            subject = 'Vaccination Alert for {}'.format(child.name)
            message = 'Dear {}, your child {} is due for the following vaccinations: {}. Please make arrangements accordingly.'.format(
                child.parent_name, child.name, ', '.join(recommended_vaccinations))
            email_from = 'your@email.com'
            recipient_list = [child.parent_email]

            send_mail(subject, message, from_email, recipient_list)

# utils.py
def get_recommended_vaccinations(age_in_months):
    # Implement your vaccination schedule logic here to return a list of recommended vaccinations based on the child's age
    # Example: vaccination_schedule = {2: ['Vaccine A'], 6: ['Vaccine B', 'Vaccine C']}
    vaccination_schedule = {
        2: ['Vaccine A'],
        6: ['Vaccine B', 'Vaccine C']
    }
    
    return vaccination_schedule.get(age_in_months, [])

    # return render(request, "daycare_staff/vaccination.html")

daycare_staff/templates/daycare_staff/attendance.html
{% extends 'daycare_staff/staff.html' %}
{% load static %}
{% block content %}
    <div class=" vh-100 attendance">
        <div class="container pt-5">
            <h2 class="text-uppercase text-center fw-bold text-primary report_font pb-4">attendance register</h2>
            <table class="table table-sm border-white text-white nutrition_style">
                <thead>
                  <tr>
                    <th scope="col">Sl No.</th>
                    <th scope="col">Child_Name</th>
                    <th scope="col">Date</th>
                    <th scope="col">Attendace_Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Hellen</td>
                    <td>20/8/2023</td>
                    <td>present</td>
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>vyom</td>
                    <td>20/8/2023</td>
                    <td>present</td>

                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td>shiya</td>
                    <td>20/8/2023</td>
                    <td>absent</td>
                </tbody>
              </table>
            </div>
            </div>
            {% endblock %}
            

daycare_staff/templates/daycare_staff/staffhome.html
{% extends 'daycare_staff/staff.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row  px-5 py-3">
        <div class="col-md-5">
    
    <div class="card card_style">



        <div class="card-body card_up">
            <h1 class="card_title fw-bold text-dark">2</h1>

            <div class="d-flex align-items-center">
                <img src="{% static 'staff_img/childlogo.jpg' %}" alt="" width="50" height="auto" class="img-fluid rounded-circle">
                <div class="ps-md-3">
                    <h4 class="text-dark fw-bold card_up">New Profile Created</h4>
                </div>
                </div>
            </div>
        </div>
    </div>
</div></div>
{% endblock %}

daycare_staff/templates/daycare_staff/viewprofile.html
{% extends 'daycare_staff/staff.html' %}
{% load static %}
{% block content %}
<div class=" vh-100 nutritions overflow-auto ">
    <div class="container pt-5">
        <h2 class="text-uppercase text-center fw-bold text-success report_font pb-4">advanced nutritions planning</h2>
        <table class="table table-sm border-dark text-dark nutrition_style">
            <thead>
              <tr>
    
                <th scope="col">Child_Name</th>
                <th scope="col">Date_of_Birth</th>
                <th scope="col">height</th>
                <th scope="col">weight</th>
                <th scope="col">Medical information</th>
                <th scope="col">Dietary Preferences/Restrictions</th>
                <th scope="col">Add Nutritions</th>
              </tr>
            </thead>
            <tbody>
             
                {% for child in all_child %}
                <tr>
                <td>{{child.name}}</td>
                <td>{{child.dateofbirth}}</td>
                <td>{{child.height}}</td>
                <td>{{child.weight}}</td>
                <td>{{child.medical_information}}</td>
                <td>{{child.dieatry_preferences}}</td>
                <td><a href="{% url 'daycare_staff:nutritions' child.id %}" class="btn btn-primary btn-sm">Click</a></td>
              </tr>
              {% endfor %}
            
            </tbody>
          </table>
        </div>
        </div>
        {% endblock %}
        